apiVersion: v1
kind: Pod
metadata:
  #name: security-context-demo
  labels:
    caller: {{ probr-caller-function }}
    feature: k-psp-012
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: "runtime/default"
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    supplementalGroups: [ 1 ]
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: psp-azp-hostport-unapproved
    image: {{ probr-compatible-image }}
    command: [ "sh", "-c", "sleep 1h" ]
    ports:
    - containerPort: {{ unapproved-port }}
      hostPort: {{ unapproved-port }}
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: [ {{ probr-cap-drop }} ]
