on:
  pull_request:
    branches: 
      - main
    paths-ignore:
      - "**/*.md"
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14.0'

    - name: Setup GO environment
      run: |
            go mod download
            go get -u golang.org/x/lint/golint
    
    - name: Lint
      run: golint ./...

    - name: Vet
      run: go vet ./...

    - name: Unit tests
      run: sudo go test ./...

    - name: Build
      run: go build -o probr ./cmd/main.go
